@extends('layouts.user_layout')
@section('content')
    @include('includes.home_haeder')
    @auth
         @include('includes.home_slider')
    @endauth
    @include('includes.track_famous_couses')
    @include('includes.home_footer')
@endsection